<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\TeachingEquipmentStandard;

class TeachingEquipmentStandardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->createPrimaryScienceStandards();
        $this->createJuniorPhysicsStandards();
        $this->createJuniorChemistryStandards();
        $this->createJuniorBiologyStandards();
        $this->createSeniorPhysicsStandards();
        $this->createSeniorChemistryStandards();
        $this->createSeniorBiologyStandards();
    }

    /**
     * 小学科学配备标准
     */
    private function createPrimaryScienceStandards()
    {
        $standards = [
            [
                'standard_name' => '小学科学教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_PRIMARY_SCIENCE_2023_001',
                'authority_type' => 1,
                'stage' => 1,
                'subject_code' => 'SCIENCE',
                'subject_name' => '科学',
                'description' => '根据教育部最新标准制定的小学科学教学仪器配备要求',
                'category_level_1' => '实验室基础器材',
                'category_level_2' => '温度测量工具',
                'item_code' => '30204001001',
                'item_name' => '红外温度仪',
                'specs_requirements' => '红外电子测温，测量范围-20~50℃',
                'unit' => '支',
                'quantity' => 48,
                'unit_price' => 45.00,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0386-2006',
                'activity_suggestion' => '温度变化观察实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '小学科学教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_PRIMARY_SCIENCE_2023_002',
                'authority_type' => 1,
                'stage' => 1,
                'subject_code' => 'SCIENCE',
                'subject_name' => '科学',
                'category_level_1' => '实验室基础器材',
                'category_level_2' => '质量测量工具',
                'item_code' => '30202000321',
                'item_name' => '托盘天平',
                'specs_requirements' => '500g，配6类M2砝码、镊子',
                'unit' => '台',
                'quantity' => 2,
                'unit_price' => 220.00,
                'is_basic' => true,
                'standard_reference' => 'QB/T 2087–2016',
                'activity_suggestion' => '物体质量测量实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '小学科学教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_PRIMARY_SCIENCE_2023_001',
                'authority_type' => 1,
                'stage' => 1,
                'subject_code' => 'SCIENCE',
                'subject_name' => '科学',
                'category_level_1' => '主题学习器材',
                'category_level_2' => '物质领域',
                'category_level_3' => '物质的特征',
                'item_code' => '30601000103',
                'item_name' => '量筒',
                'specs_requirements' => '25mL 玻璃，刻度清晰',
                'unit' => '个',
                'quantity' => 12,
                'unit_price' => 6.80,
                'is_basic' => true,
                'standard_reference' => 'GB/T 12804-2011',
                'activity_suggestion' => '探究物体体积',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '小学科学教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_PRIMARY_SCIENCE_2023_002',
                'authority_type' => 1,
                'stage' => 1,
                'subject_code' => 'SCIENCE',
                'subject_name' => '科学',
                'category_level_1' => '主题学习器材',
                'category_level_2' => '生命科学领域',
                'category_level_3' => '动物与环境',
                'item_code' => '30701002001',
                'item_name' => '放大镜',
                'specs_requirements' => '5倍，直径60mm',
                'unit' => '个',
                'quantity' => 24,
                'unit_price' => 12.50,
                'is_basic' => true,
                'standard_reference' => 'QB/T 1132-2010',
                'activity_suggestion' => '观察昆虫结构',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '小学科学教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_PRIMARY_SCIENCE_2023_003',
                'authority_type' => 1,
                'stage' => 1,
                'subject_code' => 'SCIENCE',
                'subject_name' => '科学',
                'category_level_1' => '主题学习器材',
                'category_level_2' => '地球与宇宙领域',
                'category_level_3' => '地球运动',
                'item_code' => '30801003001',
                'item_name' => '地球仪',
                'specs_requirements' => '直径20cm，政区版',
                'unit' => '个',
                'quantity' => 1,
                'unit_price' => 85.00,
                'is_basic' => true,
                'standard_reference' => 'GB/T 14511-2008',
                'activity_suggestion' => '地球自转公转演示',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '小学科学教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_PRIMARY_SCIENCE_2023_004',
                'authority_type' => 1,
                'stage' => 1,
                'subject_code' => 'SCIENCE',
                'subject_name' => '科学',
                'category_level_1' => '实验室基础器材',
                'category_level_2' => '光学器材',
                'item_code' => '30501001001',
                'item_name' => '学生显微镜',
                'specs_requirements' => '单目，10×、40×物镜',
                'unit' => '台',
                'quantity' => 12,
                'unit_price' => 380.00,
                'is_optional' => true,
                'standard_reference' => 'JY/T 0364-2004',
                'activity_suggestion' => '细胞结构观察',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ]
        ];

        foreach ($standards as $standard) {
            TeachingEquipmentStandard::create($standard);
        }
    }

    /**
     * 初中物理配备标准
     */
    private function createJuniorPhysicsStandards()
    {
        $standards = [
            [
                'standard_name' => '初中物理教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_JUNIOR_PHYSICS_2023_001',
                'authority_type' => 1,
                'stage' => 2,
                'subject_code' => 'PHYSICS',
                'subject_name' => '物理',
                'category_level_1' => '力学实验器材',
                'category_level_2' => '测力器材',
                'item_code' => '40101001001',
                'item_name' => '弹簧测力计',
                'specs_requirements' => '5N，精度0.1N',
                'unit' => '个',
                'quantity' => 25,
                'unit_price' => 18.50,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0374-2007',
                'activity_suggestion' => '力的测量实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '初中物理教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_JUNIOR_PHYSICS_2023_002',
                'authority_type' => 1,
                'stage' => 2,
                'subject_code' => 'PHYSICS',
                'subject_name' => '物理',
                'category_level_1' => '电学实验器材',
                'category_level_2' => '电源器材',
                'item_code' => '40201001001',
                'item_name' => '学生电源',
                'specs_requirements' => '直流1.5V、3V、4.5V、6V、9V',
                'unit' => '台',
                'quantity' => 13,
                'unit_price' => 125.00,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0375-2007',
                'activity_suggestion' => '电路连接实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '初中物理教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_JUNIOR_PHYSICS_2023_003',
                'authority_type' => 1,
                'stage' => 2,
                'subject_code' => 'PHYSICS',
                'subject_name' => '物理',
                'category_level_1' => '光学实验器材',
                'category_level_2' => '透镜器材',
                'item_code' => '40301001001',
                'item_name' => '凸透镜',
                'specs_requirements' => 'f=10cm，直径50mm',
                'unit' => '个',
                'quantity' => 25,
                'unit_price' => 8.50,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0376-2007',
                'activity_suggestion' => '透镜成像实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '初中物理教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_JUNIOR_PHYSICS_2023_004',
                'authority_type' => 1,
                'stage' => 2,
                'subject_code' => 'PHYSICS',
                'subject_name' => '物理',
                'category_level_1' => '热学实验器材',
                'category_level_2' => '温度测量',
                'item_code' => '40401001001',
                'item_name' => '温度计',
                'specs_requirements' => '0~100℃，精度1℃',
                'unit' => '支',
                'quantity' => 25,
                'unit_price' => 15.00,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0377-2007',
                'activity_suggestion' => '温度变化测量',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '初中物理教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_JUNIOR_PHYSICS_2023_005',
                'authority_type' => 1,
                'stage' => 2,
                'subject_code' => 'PHYSICS',
                'subject_name' => '物理',
                'category_level_1' => '声学实验器材',
                'category_level_2' => '发声器材',
                'item_code' => '40501001001',
                'item_name' => '音叉',
                'specs_requirements' => '440Hz，带共鸣箱',
                'unit' => '个',
                'quantity' => 5,
                'unit_price' => 35.00,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0378-2007',
                'activity_suggestion' => '声音传播实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '初中物理教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_JUNIOR_PHYSICS_2023_006',
                'authority_type' => 1,
                'stage' => 2,
                'subject_code' => 'PHYSICS',
                'subject_name' => '物理',
                'category_level_1' => '力学实验器材',
                'category_level_2' => '简单机械',
                'item_code' => '40102001001',
                'item_name' => '滑轮组',
                'specs_requirements' => '演示用，可组合',
                'unit' => '套',
                'quantity' => 5,
                'unit_price' => 68.00,
                'is_optional' => true,
                'standard_reference' => 'JY/T 0379-2007',
                'activity_suggestion' => '机械效率测定',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ]
        ];

        foreach ($standards as $standard) {
            TeachingEquipmentStandard::create($standard);
        }
    }

    /**
     * 初中化学配备标准
     */
    private function createJuniorChemistryStandards()
    {
        $standards = [
            [
                'standard_name' => '初中化学教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_JUNIOR_CHEMISTRY_2023_001',
                'authority_type' => 1,
                'stage' => 2,
                'subject_code' => 'CHEMISTRY',
                'subject_name' => '化学',
                'category_level_1' => '玻璃器皿',
                'category_level_2' => '反应容器',
                'item_code' => '41101001001',
                'item_name' => '试管',
                'specs_requirements' => '18×180mm，硼硅玻璃',
                'unit' => '支',
                'quantity' => 100,
                'unit_price' => 2.50,
                'is_basic' => true,
                'standard_reference' => 'GB/T 12803-2004',
                'activity_suggestion' => '化学反应实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '初中化学教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_JUNIOR_CHEMISTRY_2023_002',
                'authority_type' => 1,
                'stage' => 2,
                'subject_code' => 'CHEMISTRY',
                'subject_name' => '化学',
                'category_level_1' => '玻璃器皿',
                'category_level_2' => '测量容器',
                'item_code' => '41102001001',
                'item_name' => '量筒',
                'specs_requirements' => '50mL，A级精度',
                'unit' => '个',
                'quantity' => 25,
                'unit_price' => 12.00,
                'is_basic' => true,
                'standard_reference' => 'GB/T 12804-2011',
                'activity_suggestion' => '溶液配制实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '初中化学教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_JUNIOR_CHEMISTRY_2023_003',
                'authority_type' => 1,
                'stage' => 2,
                'subject_code' => 'CHEMISTRY',
                'subject_name' => '化学',
                'category_level_1' => '加热器材',
                'category_level_2' => '酒精灯',
                'item_code' => '41201001001',
                'item_name' => '酒精灯',
                'specs_requirements' => '150mL，带灯芯',
                'unit' => '个',
                'quantity' => 25,
                'unit_price' => 8.50,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0380-2007',
                'activity_suggestion' => '物质加热实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '初中化学教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_JUNIOR_CHEMISTRY_2023_004',
                'authority_type' => 1,
                'stage' => 2,
                'subject_code' => 'CHEMISTRY',
                'subject_name' => '化学',
                'category_level_1' => '支撑器材',
                'category_level_2' => '铁架台',
                'item_code' => '41301001001',
                'item_name' => '铁架台',
                'specs_requirements' => '高度可调，带夹具',
                'unit' => '套',
                'quantity' => 25,
                'unit_price' => 45.00,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0381-2007',
                'activity_suggestion' => '装置固定支撑',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '初中化学教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_JUNIOR_CHEMISTRY_2023_005',
                'authority_type' => 1,
                'stage' => 2,
                'subject_code' => 'CHEMISTRY',
                'subject_name' => '化学',
                'category_level_1' => '分离器材',
                'category_level_2' => '过滤器材',
                'item_code' => '41401001001',
                'item_name' => '漏斗',
                'specs_requirements' => '60mm口径，长颈',
                'unit' => '个',
                'quantity' => 25,
                'unit_price' => 6.00,
                'is_basic' => true,
                'standard_reference' => 'GB/T 28211-2011',
                'activity_suggestion' => '混合物分离实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '初中化学教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_JUNIOR_CHEMISTRY_2023_006',
                'authority_type' => 1,
                'stage' => 2,
                'subject_code' => 'CHEMISTRY',
                'subject_name' => '化学',
                'category_level_1' => '测量器材',
                'category_level_2' => '天平',
                'item_code' => '41501001001',
                'item_name' => '电子天平',
                'specs_requirements' => '精度0.1g，量程200g',
                'unit' => '台',
                'quantity' => 5,
                'unit_price' => 280.00,
                'is_optional' => true,
                'standard_reference' => 'JY/T 0382-2007',
                'activity_suggestion' => '物质质量测定',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ]
        ];

        foreach ($standards as $standard) {
            TeachingEquipmentStandard::create($standard);
        }
    }

    /**
     * 初中生物配备标准
     */
    private function createJuniorBiologyStandards()
    {
        $standards = [
            [
                'standard_name' => '初中生物教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_JUNIOR_BIOLOGY_2023_001',
                'authority_type' => 1,
                'stage' => 2,
                'subject_code' => 'BIOLOGY',
                'subject_name' => '生物',
                'category_level_1' => '观察器材',
                'category_level_2' => '显微镜',
                'item_code' => '42101001001',
                'item_name' => '生物显微镜',
                'specs_requirements' => '双目，10×、40×物镜',
                'unit' => '台',
                'quantity' => 25,
                'unit_price' => 1200.00,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0364-2004',
                'activity_suggestion' => '细胞结构观察',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '初中生物教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_JUNIOR_BIOLOGY_2023_002',
                'authority_type' => 1,
                'stage' => 2,
                'subject_code' => 'BIOLOGY',
                'subject_name' => '生物',
                'category_level_1' => '标本模型',
                'category_level_2' => '人体模型',
                'item_code' => '42201001001',
                'item_name' => '人体骨骼模型',
                'specs_requirements' => '85cm高，可拆装',
                'unit' => '个',
                'quantity' => 1,
                'unit_price' => 450.00,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0383-2007',
                'activity_suggestion' => '人体结构学习',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '初中生物教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_JUNIOR_BIOLOGY_2023_003',
                'authority_type' => 1,
                'stage' => 2,
                'subject_code' => 'BIOLOGY',
                'subject_name' => '生物',
                'category_level_1' => '实验器材',
                'category_level_2' => '解剖器材',
                'item_code' => '42301001001',
                'item_name' => '解剖器',
                'specs_requirements' => '不锈钢，含镊子、剪刀',
                'unit' => '套',
                'quantity' => 25,
                'unit_price' => 15.00,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0384-2007',
                'activity_suggestion' => '生物解剖实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '初中生物教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_JUNIOR_BIOLOGY_2023_004',
                'authority_type' => 1,
                'stage' => 2,
                'subject_code' => 'BIOLOGY',
                'subject_name' => '生物',
                'category_level_1' => '培养器材',
                'category_level_2' => '培养皿',
                'item_code' => '42401001001',
                'item_name' => '培养皿',
                'specs_requirements' => '90mm直径，玻璃',
                'unit' => '个',
                'quantity' => 50,
                'unit_price' => 3.50,
                'is_basic' => true,
                'standard_reference' => 'GB/T 12805-2011',
                'activity_suggestion' => '微生物培养实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '初中生物教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_JUNIOR_BIOLOGY_2023_005',
                'authority_type' => 1,
                'stage' => 2,
                'subject_code' => 'BIOLOGY',
                'subject_name' => '生物',
                'category_level_1' => '测量器材',
                'category_level_2' => '放大镜',
                'item_code' => '42501001001',
                'item_name' => '放大镜',
                'specs_requirements' => '10倍，直径50mm',
                'unit' => '个',
                'quantity' => 25,
                'unit_price' => 8.00,
                'is_basic' => true,
                'standard_reference' => 'QB/T 1132-2010',
                'activity_suggestion' => '植物结构观察',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '初中生物教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_JUNIOR_BIOLOGY_2023_006',
                'authority_type' => 1,
                'stage' => 2,
                'subject_code' => 'BIOLOGY',
                'subject_name' => '生物',
                'category_level_1' => '标本模型',
                'category_level_2' => '植物模型',
                'item_code' => '42202001001',
                'item_name' => '植物细胞模型',
                'specs_requirements' => '放大1000倍，彩色',
                'unit' => '个',
                'quantity' => 1,
                'unit_price' => 180.00,
                'is_optional' => true,
                'standard_reference' => 'JY/T 0385-2007',
                'activity_suggestion' => '细胞结构学习',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ]
        ];

        foreach ($standards as $standard) {
            TeachingEquipmentStandard::create($standard);
        }
    }

    /**
     * 高中物理配备标准
     */
    private function createSeniorPhysicsStandards()
    {
        $standards = [
            [
                'standard_name' => '高中物理教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_SENIOR_PHYSICS_2023_001',
                'authority_type' => 1,
                'stage' => 3,
                'subject_code' => 'PHYSICS',
                'subject_name' => '物理',
                'category_level_1' => '力学实验器材',
                'category_level_2' => '精密测量',
                'item_code' => '50101001001',
                'item_name' => '数字化力传感器',
                'specs_requirements' => '±50N，精度0.01N',
                'unit' => '个',
                'quantity' => 10,
                'unit_price' => 380.00,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0390-2007',
                'activity_suggestion' => '牛顿定律验证',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '高中物理教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_SENIOR_PHYSICS_2023_002',
                'authority_type' => 1,
                'stage' => 3,
                'subject_code' => 'PHYSICS',
                'subject_name' => '物理',
                'category_level_1' => '电学实验器材',
                'category_level_2' => '数字化设备',
                'item_code' => '50201001001',
                'item_name' => '数字万用表',
                'specs_requirements' => '3½位，自动量程',
                'unit' => '台',
                'quantity' => 25,
                'unit_price' => 150.00,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0391-2007',
                'activity_suggestion' => '电路参数测量',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '高中物理教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_SENIOR_PHYSICS_2023_003',
                'authority_type' => 1,
                'stage' => 3,
                'subject_code' => 'PHYSICS',
                'subject_name' => '物理',
                'category_level_1' => '光学实验器材',
                'category_level_2' => '激光器材',
                'item_code' => '50301001001',
                'item_name' => '激光器',
                'specs_requirements' => '红光，功率<1mW',
                'unit' => '台',
                'quantity' => 5,
                'unit_price' => 280.00,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0392-2007',
                'activity_suggestion' => '光的干涉衍射实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '高中物理教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_SENIOR_PHYSICS_2023_004',
                'authority_type' => 1,
                'stage' => 3,
                'subject_code' => 'PHYSICS',
                'subject_name' => '物理',
                'category_level_1' => '现代物理器材',
                'category_level_2' => '原子物理',
                'item_code' => '50401001001',
                'item_name' => '盖革计数器',
                'specs_requirements' => '数字显示，带探头',
                'unit' => '台',
                'quantity' => 2,
                'unit_price' => 1200.00,
                'is_optional' => true,
                'standard_reference' => 'JY/T 0393-2007',
                'activity_suggestion' => '放射性检测实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '高中物理教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_SENIOR_PHYSICS_2023_005',
                'authority_type' => 1,
                'stage' => 3,
                'subject_code' => 'PHYSICS',
                'subject_name' => '物理',
                'category_level_1' => '热学实验器材',
                'category_level_2' => '温度传感器',
                'item_code' => '50501001001',
                'item_name' => '数字温度计',
                'specs_requirements' => '-50~150℃，精度0.1℃',
                'unit' => '支',
                'quantity' => 25,
                'unit_price' => 85.00,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0394-2007',
                'activity_suggestion' => '热力学定律验证',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '高中物理教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_SENIOR_PHYSICS_2023_006',
                'authority_type' => 1,
                'stage' => 3,
                'subject_code' => 'PHYSICS',
                'subject_name' => '物理',
                'category_level_1' => '波动实验器材',
                'category_level_2' => '示波器',
                'item_code' => '50601001001',
                'item_name' => '数字示波器',
                'specs_requirements' => '双通道，100MHz',
                'unit' => '台',
                'quantity' => 5,
                'unit_price' => 2800.00,
                'is_optional' => true,
                'standard_reference' => 'JY/T 0395-2007',
                'activity_suggestion' => '波形分析实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ]
        ];

        foreach ($standards as $standard) {
            TeachingEquipmentStandard::create($standard);
        }
    }

    /**
     * 高中化学配备标准
     */
    private function createSeniorChemistryStandards()
    {
        $standards = [
            [
                'standard_name' => '高中化学教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_SENIOR_CHEMISTRY_2023_001',
                'authority_type' => 1,
                'stage' => 3,
                'subject_code' => 'CHEMISTRY',
                'subject_name' => '化学',
                'category_level_1' => '精密仪器',
                'category_level_2' => '分析天平',
                'item_code' => '51101001001',
                'item_name' => '电子分析天平',
                'specs_requirements' => '精度0.0001g，量程220g',
                'unit' => '台',
                'quantity' => 2,
                'unit_price' => 8500.00,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0396-2007',
                'activity_suggestion' => '定量分析实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '高中化学教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_SENIOR_CHEMISTRY_2023_002',
                'authority_type' => 1,
                'stage' => 3,
                'subject_code' => 'CHEMISTRY',
                'subject_name' => '化学',
                'category_level_1' => '测量仪器',
                'category_level_2' => 'pH计',
                'item_code' => '51201001001',
                'item_name' => '数字pH计',
                'specs_requirements' => '精度0.01，自动温补',
                'unit' => '台',
                'quantity' => 5,
                'unit_price' => 450.00,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0397-2007',
                'activity_suggestion' => '酸碱滴定实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '高中化学教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_SENIOR_CHEMISTRY_2023_003',
                'authority_type' => 1,
                'stage' => 3,
                'subject_code' => 'CHEMISTRY',
                'subject_name' => '化学',
                'category_level_1' => '加热设备',
                'category_level_2' => '电热板',
                'item_code' => '51301001001',
                'item_name' => '数显电热板',
                'specs_requirements' => '温控范围50-300℃',
                'unit' => '台',
                'quantity' => 10,
                'unit_price' => 380.00,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0398-2007',
                'activity_suggestion' => '有机合成实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '高中化学教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_SENIOR_CHEMISTRY_2023_004',
                'authority_type' => 1,
                'stage' => 3,
                'subject_code' => 'CHEMISTRY',
                'subject_name' => '化学',
                'category_level_1' => '分离设备',
                'category_level_2' => '离心机',
                'item_code' => '51401001001',
                'item_name' => '台式离心机',
                'specs_requirements' => '最高转速4000rpm',
                'unit' => '台',
                'quantity' => 2,
                'unit_price' => 1200.00,
                'is_optional' => true,
                'standard_reference' => 'JY/T 0399-2007',
                'activity_suggestion' => '胶体分离实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '高中化学教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_SENIOR_CHEMISTRY_2023_005',
                'authority_type' => 1,
                'stage' => 3,
                'subject_code' => 'CHEMISTRY',
                'subject_name' => '化学',
                'category_level_1' => '光谱仪器',
                'category_level_2' => '分光光度计',
                'item_code' => '51501001001',
                'item_name' => '可见分光光度计',
                'specs_requirements' => '波长范围400-700nm',
                'unit' => '台',
                'quantity' => 1,
                'unit_price' => 15000.00,
                'is_optional' => true,
                'standard_reference' => 'JY/T 0400-2007',
                'activity_suggestion' => '物质浓度测定',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '高中化学教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_SENIOR_CHEMISTRY_2023_006',
                'authority_type' => 1,
                'stage' => 3,
                'subject_code' => 'CHEMISTRY',
                'subject_name' => '化学',
                'category_level_1' => '安全设备',
                'category_level_2' => '通风橱',
                'item_code' => '51601001001',
                'item_name' => '实验室通风橱',
                'specs_requirements' => '1.2m宽，变风量控制',
                'unit' => '台',
                'quantity' => 2,
                'unit_price' => 12000.00,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0401-2007',
                'activity_suggestion' => '有害气体实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ]
        ];

        foreach ($standards as $standard) {
            TeachingEquipmentStandard::create($standard);
        }
    }

    /**
     * 高中生物配备标准
     */
    private function createSeniorBiologyStandards()
    {
        $standards = [
            [
                'standard_name' => '高中生物教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_SENIOR_BIOLOGY_2023_001',
                'authority_type' => 1,
                'stage' => 3,
                'subject_code' => 'BIOLOGY',
                'subject_name' => '生物',
                'category_level_1' => '精密仪器',
                'category_level_2' => '荧光显微镜',
                'item_code' => '52101001001',
                'item_name' => '荧光显微镜',
                'specs_requirements' => '三目，LED光源',
                'unit' => '台',
                'quantity' => 2,
                'unit_price' => 25000.00,
                'is_optional' => true,
                'standard_reference' => 'JY/T 0402-2007',
                'activity_suggestion' => '细胞荧光标记观察',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '高中生物教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_SENIOR_BIOLOGY_2023_002',
                'authority_type' => 1,
                'stage' => 3,
                'subject_code' => 'BIOLOGY',
                'subject_name' => '生物',
                'category_level_1' => '培养设备',
                'category_level_2' => '恒温培养箱',
                'item_code' => '52201001001',
                'item_name' => '生化培养箱',
                'specs_requirements' => '温控范围5-50℃',
                'unit' => '台',
                'quantity' => 2,
                'unit_price' => 3500.00,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0403-2007',
                'activity_suggestion' => '微生物培养实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '高中生物教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_SENIOR_BIOLOGY_2023_003',
                'authority_type' => 1,
                'stage' => 3,
                'subject_code' => 'BIOLOGY',
                'subject_name' => '生物',
                'category_level_1' => '分析仪器',
                'category_level_2' => '电泳仪',
                'item_code' => '52301001001',
                'item_name' => '水平电泳仪',
                'specs_requirements' => '凝胶板10×8cm',
                'unit' => '套',
                'quantity' => 5,
                'unit_price' => 1200.00,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0404-2007',
                'activity_suggestion' => 'DNA电泳分析',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '高中生物教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_SENIOR_BIOLOGY_2023_004',
                'authority_type' => 1,
                'stage' => 3,
                'subject_code' => 'BIOLOGY',
                'subject_name' => '生物',
                'category_level_1' => '测量仪器',
                'category_level_2' => '分光光度计',
                'item_code' => '52401001001',
                'item_name' => '紫外分光光度计',
                'specs_requirements' => '波长范围200-800nm',
                'unit' => '台',
                'quantity' => 1,
                'unit_price' => 18000.00,
                'is_optional' => true,
                'standard_reference' => 'JY/T 0405-2007',
                'activity_suggestion' => '蛋白质浓度测定',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '高中生物教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_SENIOR_BIOLOGY_2023_005',
                'authority_type' => 1,
                'stage' => 3,
                'subject_code' => 'BIOLOGY',
                'subject_name' => '生物',
                'category_level_1' => '制备设备',
                'category_level_2' => '超净工作台',
                'item_code' => '52501001001',
                'item_name' => '生物安全柜',
                'specs_requirements' => 'II级A2型，1.2m宽',
                'unit' => '台',
                'quantity' => 1,
                'unit_price' => 15000.00,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0406-2007',
                'activity_suggestion' => '无菌操作实验',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ],
            [
                'standard_name' => '高中生物教学仪器配备标准（教育部）',
                'standard_code' => 'MOE_SENIOR_BIOLOGY_2023_006',
                'authority_type' => 1,
                'stage' => 3,
                'subject_code' => 'BIOLOGY',
                'subject_name' => '生物',
                'category_level_1' => '模型标本',
                'category_level_2' => 'DNA模型',
                'item_code' => '52601001001',
                'item_name' => 'DNA双螺旋模型',
                'specs_requirements' => '可拆装，彩色编码',
                'unit' => '套',
                'quantity' => 5,
                'unit_price' => 280.00,
                'is_basic' => true,
                'standard_reference' => 'JY/T 0407-2007',
                'activity_suggestion' => '分子结构学习',
                'version' => '2023.1',
                'effective_date' => '2023-09-01',
                'status' => 1,
            ]
        ];

        foreach ($standards as $standard) {
            TeachingEquipmentStandard::create($standard);
        }
    }
}
